wandb_version: 1

name:
  desc: null
  value: CVHSSR-T_x4_baseline
model_type:
  desc: null
  value: ImageRestorationModel
scale:
  desc: null
  value: 4
num_gpu:
  desc: null
  value: 1
manual_seed:
  desc: null
  value: 10
datasets:
  desc: null
  value:
    train:
      name: Flickr1024-sr-train
      type: PairedStereoImageDataset
      dataroot_gt: ./dataset/Train/HR
      dataroot_lq: ./dataset/Train/LR_x4
      io_backend:
        type: disk
      gt_size_h: 120
      gt_size_w: 360
      use_hflip: true
      use_vflip: true
      use_rot: false
      flip_RGB: true
      use_shuffle: true
      num_worker_per_gpu: 8
      batch_size_per_gpu: 12
      dataset_enlarge_ratio: 1
      prefetch_mode: null
      phase: train
      scale: 4
    val:
      name: Flickr1024-sr-test
      type: PairedStereoImageDataset
      dataroot_gt: ./dataset/val/HR
      dataroot_lq: ./dataset/val/LR_x4
      io_backend:
        type: disk
      phase: val
      scale: 4
network_g:
  desc: null
  value:
    type: CVHSSR
    up_scale: 4
    width: 48
    num_blks: 16
    drop_path_rate: 0
    train_size:
    - 1
    - 6
    - 30
    - 90
    drop_out_rate: 0.0
path:
  desc: null
  value:
    pretrain_network_g: null
    strict_load_g: true
    resume_state: null
    root: /root/autodl-tmp/CVHSSR
    experiments_root: /root/autodl-tmp/CVHSSR/experiments/CVHSSR-T_x4_baseline
    models: /root/autodl-tmp/CVHSSR/experiments/CVHSSR-T_x4_baseline/models
    training_states: /root/autodl-tmp/CVHSSR/experiments/CVHSSR-T_x4_baseline/training_states
    log: /root/autodl-tmp/CVHSSR/experiments/CVHSSR-T_x4_baseline
    visualization: /root/autodl-tmp/CVHSSR/experiments/CVHSSR-T_x4_baseline/visualization
train:
  desc: null
  value:
    optim_g:
      type: Lion
      lr: 0.0001
      weight_decay: 0.0
      betas:
      - 0.9
      - 0.9
    scheduler:
      type: TrueCosineAnnealingLR
      T_max: 200000
      eta_min: 1.0e-08
    total_iter: 200000
    warmup_iter: -1
    mixup: false
    pixel_opt:
      type: ComposeLoss
      loss_weight: 0.01
      reduction: mean
val:
  desc: null
  value:
    val_freq: 10000.0
    save_img: false
    trans_num: 1
    max_minibatch: 1
    metrics:
      psnr:
        type: calculate_psnr
        crop_border: 0
        test_y_channel: false
      ssim:
        type: calculate_skimage_ssim
logger:
  desc: null
  value:
    print_freq: 200
    save_checkpoint_freq: 10000.0
    use_tb_logger: true
    wandb:
      project: CVHSSR_T_baseline
      resume_id: null
dist_params:
  desc: null
  value:
    backend: nccl
    port: 29500
is_train:
  desc: null
  value: true
dist:
  desc: null
  value: true
rank:
  desc: null
  value: 0
world_size:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707842484.872501
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 35
      4: 3.8.10
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
